<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<p style="margin: 6.0pt 2.85pt;text-align: justify;"><span style=""> <span style="color: rgb(0,0,0);"> <span style="line-height: 20.0px;"> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;">Chào mừng quý khách đến với PostID.</span></span></span></span></span></p>

<p style="margin: 6.0pt 2.85pt;text-align: justify;"><span style=""> <span style="color: rgb(0,0,0);"> <span style="line-height: 20.0px;"> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;">Cảm ơn quý khách đã sử dụng các dịch vụ của chúng tôi (“Dịch vụ”). Dịch vụ PostID được cung cấp bởi Tổng công ty Bưu điệnViệt Nam có trụ sở tại số 5 đường Phạm Hùng, phường Mai Dịch, quận Nam Từ Liêm, thành phố Hà Nội.</span></span></span></span></span></p>

<p style="margin: 6.0pt 2.85pt;text-align: justify;"><span style=""> <span style="color: rgb(0,0,0);"> <span style="line-height: 20.0px;"> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;">Để sử dụng dịch vụ PostID của chúng tôi, quý khách vui lòng đọc kỹ và chấp thuận các Điều Khoản Sử Dụng dưới đây. Nếu có bất kỳ câu hỏi nào về việc sử dụng PostID xin gửi về địa chỉ email……., tất cả câu hỏi sẽ được chúng tôi giải đáp.</span></span></span></span></span></p>

<p style="margin: 6.0pt 2.85pt;text-align: justify;"><span style=""> <span style="color: rgb(0,0,0);"> <span style="line-height: 20.0px;"> <b> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;">Điều 1: Giải thích từ ngữ</span></span></b></span></span></span></p>

<ol>
	<li style="margin-top: 6.0pt;margin-right: 2.85pt;margin-bottom: 6.0pt;text-align: justify;"><span style="line-height: 150.0%;"> <span style=""> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;">“<b>VNPost</b>” có nghĩa là Tổng công ty Bưu điện Việt Nam - doanh nghiệp 100% vốn Nhà nước được chỉ định thực hiện duy trì, quản lý mạng bưu chính công cộng, cung ứng dịch vụ bưu chính công ích, dịch vụ bưu chính quốc tế, cung cấp dịch vụ công trực tuyến trên cổng dịch vụ công quốc gia;</span></span></span></span></li>
	<li style="margin-top: 6.0pt;margin-right: 2.85pt;margin-bottom: 6.0pt;text-align: justify;"><span style="line-height: 150.0%;"> <span style=""> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;">“<b>PostID</b>” có nghĩa là tài khoản do Người Sử Dụng mở, có thể đăng nhập vào hệ thống của Bưu điện để sử dụng các dịch vụ do Bưu điện cung cấp. Ngoài ra có thể sử dụng PostID đăng nhập vào hệ thống của các đơn vị khác có kết nối với Bưu điện để sử dụng dịch vụ mà không cần khai báo, tạo tài khoản, xác thực thông tin;</span></span></span></span></li>
	<li style="margin-top: 6.0pt;margin-right: 2.85pt;margin-bottom: 6.0pt;text-align: justify;"><span style="line-height: 150.0%;"> <span style=""> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;">“<b>Người Sử Dụng</b>” có nghĩa là cá nhân hoặc tổ chức sử dụng PostID của VNPost;</span></span></span></span></li>
	<li style="margin-top: 6.0pt;margin-right: 2.85pt;margin-bottom: 6.0pt;text-align: justify;"><span style="line-height: 150.0%;"> <span style=""> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;">“<b>Bên</b>” có nghĩa là Người Sử Dụng hoặc VNPost và “<b>Các bên</b>” có nghĩa là Người Sử Dụng và VNPost;</span></span></span></span></li>
	<li style="margin-top: 6.0pt;margin-right: 2.85pt;margin-bottom: 6.0pt;text-align: justify;"><span style="line-height: 150.0%;"> <span style=""> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;">“<b>Định danh xác thực điện tử</b>” có nghĩa là quá trình xác định danh tính điện tử của cá nhân, tổ chức và xác minh danh tính điện tử của người sử dụng.</span></span></span></span></li>
</ol>

<p style="margin: 6.0pt 2.85pt;text-align: justify;"><span style=""> <span style="color: rgb(0,0,0);"> <span style="line-height: 20.0px;"> <b> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;">Điều 2: Tạo lập, sử dụng và quản lý tài khoản</span></span></b></span></span></span></p>

<ol>
	<li style="margin-top: 6.0pt;margin-right: 2.85pt;margin-bottom: 6.0pt;text-align: justify;"><span style="line-height: 150.0%;"> <span style=""> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;">Để tạo lập và sử dụng PostID, Người Sử Dụng sẽ phải kê khai, cung cấp cho VNPost các thông tin, tài liệu theo quy định của VNPost tại từng thời điểm. Người sử dụng đảm bảo rằng các thông tin kê khai, cung cấp trong hồ sơ mở PostID là chính xác và đúng sự thật. Người Sử Dụng chịu trách nhiệm về các thông tin liên quan được cung cấp cho VNPost trong quá trình sử dụng PostID. Nếu có bất cứ thay đổi nào so với thông tin đã kê khai hoặc cung cấp cho VNPost, Người Sử Dụng kịp thời thông báo cho VNPost.</span></span></span></span></li>
	<li style="margin-top: 6.0pt;margin-right: 2.85pt;margin-bottom: 6.0pt;text-align: justify;"><span style="line-height: 150.0%;"> <span style=""> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);"> <span style="background-color: white;"> <span style=""> <span style="">Người Sử Dụng có trách nhiệm bổ sung thêm các thông tin liên quan theo yêu cầu của VNPost</span></span></span></span></span></span> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);"> <span style="background-color: white;"> <span style=""> <span style="">.</span></span></span></span></span></span></span></span></li>
	<li style="margin-top: 6.0pt;margin-right: 2.85pt;margin-bottom: 6.0pt;text-align: justify;"><span style="line-height: 150.0%;"> <span style=""> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);"> <span style="background-color: white;"> <span style=""> <span style="">Người Sử Dụng cam đoan và bảo đảm rằng địa chỉ thư điện tử mà Người Sử Dụng đăng ký sử dụng PostID phải là địa chỉ hợp lệ, đã được kích hoạt, đang hoạt động và chỉ có Người Sử Dụng có quyền truy cập và sử dụng hợp pháp.</span></span></span></span></span></span></span></span></li>
	<li style="margin-top: 6.0pt;margin-right: 2.85pt;margin-bottom: 6.0pt;text-align: justify;"><span style="line-height: 150.0%;"> <span style=""> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);"> <span style="background-color: white;"> <span style=""> <span style="">Người Sử Dụng cam đoan và bảo đảm rằng số điện thoại Người Sử Dụng đăng ký sử dụng </span></span></span></span></span></span> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);"> <span style="background-color: white;"> <span style=""> <span style="">PostID</span></span></span></span></span></span> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);"> <span style="background-color: white;"> <span style=""> <span style="">phải là thuê bao đã được kích hoạt và đang hoạt động hợp lệ, và Người Sử Dụng có đầy đủ quyền sở hữu, truy cập, sử dụng hợp pháp, hợp lệ số điện thoại này.</span></span></span></span></span></span></span></span></li>
	<li style="margin-top: 6.0pt;margin-right: 2.85pt;margin-bottom: 6.0pt;text-align: justify;"><span style="background: white;"> <span style="line-height: 150.0%;"> <span style=""> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">VNPost</span></span></span> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">sẽ có quyền tạm khóa hoặc đóng PostID mà không cần bất cứ thông báo và/hoặc chấp thuận trước của Người Sử Dụng trong các trường hợp sau:</span></span></span></span></span></span></li>
</ol>

<ol style="list-style-type: lower-alpha;">
	<li style="margin-top: 6.0pt;margin-right: 2.85pt;margin-bottom: 6.0pt;text-align: justify;"><span style="background: white;"> <span style="line-height: 150.0%;"> <span style=""> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">Theo văn bản yêu cầu đóng PostID của Người Sử Dụng;</span></span></span></span></span></span></li>
</ol>

<p style="margin: 6.0pt 2.85pt;text-align: justify;"><span style=""> <span style="color: rgb(0,0,0);"> <span style="line-height: 20.0px;"> <span style="background-color: white;"> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">(</span></span></span> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">b</span></span></span> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">) Khi Người Sử Dụng là cá nhân mất năng lực hành vi dân sự hoặc chết, hoặc bị tuyên bố là đã chết hoặc bị tuyên bố mất tích;</span></span></span></span></span></span></span></p>

<p style="margin: 6.0pt 2.85pt;text-align: justify;"><span style=""> <span style="color: rgb(0,0,0);"> <span style="line-height: 20.0px;"> <span style="background-color: white;"> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">(</span></span></span> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">c</span></span></span> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">) Khi Người Sử Dụng là tổ chức giải thể hoặc chấm dứt hoạt động dưới bất cứ hình thức nào;</span></span></span></span></span></span></span></p>

<p style="margin: 6.0pt 2.85pt;text-align: justify;"><span style=""> <span style="color: rgb(0,0,0);"> <span style="line-height: 20.0px;"> <span style="background-color: white;"> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">(</span></span></span> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">d</span></span></span> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">) VNPost</span></span></span> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">phát hiện PostID được mở vi phạm các quy định pháp luật, quy trình nội bộ của VNPost</span></span></span> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">về quản lý </span></span></span> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">PostID</span></span></span> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);"> trong từng thời kỳ;</span></span></span></span></span></span></span></p>

<p style="margin: 6.0pt 2.85pt;text-align: justify;"><span style=""> <span style="color: rgb(0,0,0);"> <span style="line-height: 20.0px;"> <span style="background-color: white;"> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">(</span></span></span> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">e</span></span></span> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">) Khi vi phạm bất cứ quy định nào tại Điều </span></span></span> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">khoản Sử dụng này hoặc </span></span></span> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">các chính sách </span></span></span> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">khác </span></span></span> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">của </span></span></span> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">VNPost,</span></span></span> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">Người Sử Dụng sở hữu </span></span></span> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">PostID</span></span></span> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">sẽ</span></span></span> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);"> bị tạm khóa/khóa vĩnh viễn.</span></span></span></span></span></span></span></p>

<p style="margin: 6.0pt 2.85pt;text-align: justify;"><span style=""> <span style="color: rgb(0,0,0);"> <span style="line-height: 20.0px;"> <span style="background-color: white;"> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">(g) Trường hợp khác theo yêu cầu của VNPost.</span></span></span></span></span></span></span></p>

<p style="margin: 6.0pt 2.85pt;text-align: justify;"><span style=""> <span style="color: rgb(0,0,0);"> <span style="line-height: 20.0px;"> <span style="background-color: white;"> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">6. </span></span></span> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">Người Sử Dụng phải tự bảo quản các thiết bị cài đặt PostID và bảo mật các mật khẩu, mật mã, các thông tin xác thực, xác nhận và thông tin định danh khác của Người Sử Dụng liên quan đến PostID. Mọi yêu cầu giao dịch được thực hiện trên PostID theo đúng thao tác, quy trình, bao gồm nhưng không giới hạn ở các bước xác thực khách hàng, xác thực giao dịch của VNPost</span></span></span> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">sẽ luôn được coi là yêu cầu của chính Người Sử Dụng. VNPost</span></span></span> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">sẽ không chịu bất cứ trách nhiệm nào phát sinh từ việc Người Sử Dụng để thất lạc các thiết bị cài đặt PostID hoặc bị đánh cắp các mật khẩu, mật mã, các thông tin xác thực, xác nhận và thông tin định danh khác của Người Sử Dụng liên quan đến PostID.</span></span></span></span></span></span></span></p>

<p style="margin: 6.0pt 2.85pt;text-align: justify;"><span style=""> <span style="color: rgb(0,0,0);"> <span style="line-height: 20.0px;"> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);"> <span style="background-color: white;"> <span style=""> <span style="">7. </span></span></span></span></span></span> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);"> <span style="background-color: white;"> <span style=""> <span style="">Trường hợp bị lộ các thông tin bảo mật, thông tin xác thực, định danh của Người Sử Dụng, Người Sử Dụng phải ngay lập tức thông báo cho VNPost</span></span></span></span></span></span> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);"> <span style="background-color: white;"> <span style=""> <span style="">và thực hiện các thủ tục cần thiết để được hỗ trợ tạm ngừng/tạm khóa PostID. Trường hợp không thông báo hoặc không thông báo kịp thời, Người Sử Dụng sẽ chịu toàn bộ trách nhiệm đối với các tổn thất phát sinh cho đến thời điểm hoàn tất các thủ tục thông báo cho V</span></span></span></span></span></span> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);"> <span style="background-color: white;"> <span style=""> <span style="">NPost</span></span></span></span></span></span> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);"> <span style="background-color: white;"> <span style=""> <span style="">.</span></span></span></span></span></span></span></span></span></p>

<p style="margin: 6.0pt 2.85pt;text-align: justify;"><span style=""> <span style="color: rgb(0,0,0);"> <span style="line-height: 20.0px;"> <b> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;">Điều 3: Quyền lợi và trách nhiệm của người sử dụng</span></span></b></span></span></span></p>

<ol>
	<li style="margin-top: 6.0pt;margin-right: 2.85pt;margin-bottom: 6.0pt;text-align: justify;"><span style="line-height: 150.0%;"> <span style=""> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;">Người Sử Dụng tài khoản PostID đã được cấp đăng nhập vào các hệ thống của VNPost để sử dụng các dịch vụ do VNPost cung cấp.</span></span></span></span></li>
	<li style="margin-top: 6.0pt;margin-right: 2.85pt;margin-bottom: 6.0pt;text-align: justify;"><span style="line-height: 150.0%;"> <span style=""> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;">Người Sử Dụng sử dụng tài khoản PostID để đăng nhập vào Cổng Dịch vụ Công Quốc gia.</span></span></span></span></li>
	<li style="margin-top: 6.0pt;margin-right: 2.85pt;margin-bottom: 6.0pt;text-align: justify;"><span style="line-height: 150.0%;"> <span style=""> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;">Người Sử Dụng được sử dụng thêm các dịch vụ khác mà không cần phải xác thực lại thông tin.</span></span></span></span></li>
	<li style="margin-top: 6.0pt;margin-right: 2.85pt;margin-bottom: 6.0pt;text-align: justify;"><span style="line-height: 150.0%;"> <span style=""> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;">Người Sử Dụng được xác thực thông tin với bên thứ ba thông qua PostID. </span></span></span></span></li>
</ol>

<p style="margin: 6.0pt 2.85pt;text-align: justify;"><span style=""> <span style="color: rgb(0,0,0);"> <span style="line-height: 20.0px;"> <b> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;">Điều 4: Phạm vi trách nhiệm của VN Post</span></span></b></span></span></span></p>

<ol>
	<li style="margin-top: 6.0pt;margin-right: 2.85pt;margin-bottom: 6.0pt;text-align: justify;"><span style="line-height: 150.0%;"> <span style=""> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;">Trong mọi trường hợp, trách nhiệm của VNPost sẽ được giới hạn ở những nội dung sau đây:</span></span></span></span></li>
</ol>

<ol style="list-style-type: lower-alpha;">
	<li style="margin-top: 6.0pt;margin-right: 2.85pt;margin-bottom: 6.0pt;text-align: justify;"><span style="line-height: 150.0%;"> <span style=""> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;">Ngoại trừ các điều khoản được quy định cụ thể tại Điều khoản Sử dụng này và các thỏa thuận khác bằng văn bản của VNPost, VNPost sẽ không bị ràng buộc bởi thoả thuận nào giữa Người Sử Dụng và/hoặc bất cứ bên thứ ba.</span></span></span></span></li>
	<li style="margin-top: 6.0pt;margin-right: 2.85pt;margin-bottom: 6.0pt;text-align: justify;"><span style="line-height: 150.0%;"> <span style=""> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;">VNPost sẽ không phải thực hiện nghĩa vụ nào của mình theo Điều khoản Sử dụng này hoặc văn bản thỏa thuận nếu việc thực hiện đó sẽ dẫn đến việc VNPost vi phạm quy định Pháp luật hoặc văn bản khác của cơ quan Nhà nước có thẩm quyền.</span></span></span></span></li>
	<li style="margin-top: 6.0pt;margin-right: 2.85pt;margin-bottom: 6.0pt;text-align: justify;"><span style="line-height: 150.0%;"> <span style=""> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;">Nếu VNPost theo quyết định của cơ quan có thẩm quyền, phải chịu trách nhiệm về các tổn thất, thiệt hại phát sinh cho Người Sử Dụng và/hoặc bất cứ bên thứ ba nào liên quan đến việc cung cấp PostID của VNPost, trách nhiệm của VNPost trong mọi trường hợp sẽ không vượt quá số tiền cước phí dịch vụ mà VNPost đã nhận được trên thực tế.</span></span></span></span></li>
	<li style="margin-top: 6.0pt;margin-right: 2.85pt;margin-bottom: 6.0pt;text-align: justify;"><span style="line-height: 150.0%;"> <span style=""> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;">VNPost không phải chịu trách nhiệm trong trường hợp Người Sử Dụng cung cấp thông tin không chính xác.</span></span></span></span></li>
</ol>

<ol>
	<li style="margin-top: 6.0pt;margin-right: 2.85pt;margin-bottom: 6.0pt;text-align: justify;"><span style="line-height: 150.0%;"> <span style=""> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;">Người Sử Dụng sẽ bồi hoàn và giữ cho VNPost vô hại khỏi mọi tranh chấp, thiệt hại, tổn thất liên quan đến Giao Dịch. Để làm rõ, phạm vi bồi hoàn tại Khoản này là tất cả các thiệt hại, tổn thất, chi phí mà VNPost có thể phải gánh chịu trong trường hợp VNPost phải tham gia vào quá trình giải quyết các yêu cầu, khiếu nại, khiếu kiện, thủ tục tố tụng liên quan đến Giao Dịch bao gồm nhưng không giới hạn ở các chi phí hành chính, phí tố tụng, phí luật sư và chi phí ăn ở, đi lại.</span></span></span></span></li>
</ol>

<p style="margin: 6.0pt 2.85pt;text-align: justify;"><span style=""> <span style="color: rgb(0,0,0);"> <span style="line-height: 20.0px;"> <b> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;">Điều 5: Bảo mật và sử dụng thông tin</span></span></b></span></span></span></p>

<ol>
	<li style="margin-top: 6.0pt;margin-right: 2.85pt;margin-bottom: 6.0pt;text-align: justify;"><span style="background: white;"> <span style="line-height: 150.0%;"> <span style=""> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">Đối với Người Sử Dụng</span></span></span></span></span></span></li>
</ol>

<p style="margin: 6.0pt 2.85pt;text-align: justify;"><span style=""> <span style="color: rgb(0,0,0);"> <span style="line-height: 20.0px;"> <span style="background-color: white;"> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">(a) </span></span></span> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">Các</span></span></span> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);"> thông tin, tài liệu và dữ liệu nào VNPost cung cấp cho Người Sử Dụng </span></span></span> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">đều</span></span></span> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);"> được coi là thông tin mật. Người Sử Dụng cam kết chỉ sử dụng các thông tin mật này để thực hiện Giao Dịch và không </span></span></span> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">cung cấp cho</span></span></span> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);"> bên thứ ba nào nếu không có sự đồng ý bằng văn bản của VNPost.</span></span></span></span></span></span></span></p>

<p style="margin: 6.0pt 2.85pt;text-align: justify;"><span style=""> <span style="color: rgb(0,0,0);"> <span style="line-height: 20.0px;"> <span style="background-color: white;"> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">(b) Nếu Người Sử Dụng </span></span></span> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">cung cấp</span></span></span> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);"> thông tin mật theo quy định của pháp luật hoặc theo yêu cầu, mệnh lệnh của cơ quan có thẩm quyền, Người Sử Dụng phải thông báo trước bằng văn bản cho VNPost để tìm phương án giảm thiểu tối đa phạm vi thông tin mật phải </span></span></span> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">cung cấp</span></span></span> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">.</span></span></span></span></span></span></span></p>

<p style="margin: 6.0pt 2.85pt;text-align: justify;"><span style=""> <span style="color: rgb(0,0,0);"> <span style="line-height: 20.0px;"> <span style="background-color: white;"> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">(c) Tất cả các tài liệu, dưới hình thức văn bản hoặc thư điện tử, có chứa thông tin mật mà Người Sử Dụng nhận được từ VNPost hoặc có được liên quan đến các công việc tại Các Văn Kiện Giao Dịch sẽ thuộc sở hữu của VNPost . Các tài liệu đó và những thông tin mật khác, kể cả những bản sao chép hoặc những đoạn trích dẫn của thông tin mật, ngay tại thời điểm VNPost yêu cầu, Người Sử Dụng phải hoàn trả ngay lập tức hoặc tiêu hủy.</span></span></span></span></span></span></span></p>

<p style="margin: 6.0pt 2.85pt;text-align: justify;"><span style=""> <span style="color: rgb(0,0,0);"> <span style="line-height: 20.0px;"> <span style="background-color: white;"> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">(d)</span></span></span> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);"> Nghĩa vụ bảo mật và không sử dụng thông tin mật quy định tại Khoản này sẽ tiếp tục duy trì hiệu lực sau khi Các Văn Kiện Giao Dịch chấm dứt hiệu lực.</span></span></span></span></span></span></span></p>

<ol>
	<li style="margin-top: 6.0pt;margin-right: 2.85pt;margin-bottom: 6.0pt;text-align: justify;"><span style="background: white;"> <span style="line-height: 150.0%;"> <span style=""> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">Đối với VNPost</span></span></span></span></span></span></li>
</ol>

<p style="margin: 6.0pt 2.85pt;text-align: justify;"><span style=""> <span style="color: rgb(0,0,0);"> <span style="line-height: 20.0px;"> <span style="background-color: white;"> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">(a)</span></span></span> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">VNPost </span></span></span> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">được</span></span></span> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);"> thu thập, lưu trữ, </span></span></span> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">sử dụng</span></span></span> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);"> các thông tin</span></span></span> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">, giao dịch liên quan đến </span></span></span> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">Người Sử Dụng</span></span></span> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);"> thông qua PostID nhằm cung cấp các dịch vụ theo chính sách của VNPost tại từng thời điểm</span></span></span> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">.</span></span></span> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);"> Trường hợp cung cấp thông tin cho bên thứ ba nào khác phải có sự đồng ý của Người Sử Dụng</span></span></span></span></span></span></span></p>

<p style="margin: 6.0pt 2.85pt;text-align: justify;"><span style=""> <span style="color: rgb(0,0,0);"> <span style="line-height: 20.0px;"> <span style="background-color: white;"> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">(b) Tất cả các Thông Tin Người Sử Dụng do VNPost nắm giữ sẽ được nỗ lực bảo vệ ở mức độ hợp lý tránh việc bị xâm nhập hoặc tiết lộ trái phép.</span></span></span></span></span></span></span></p>

<p style="margin: 6.0pt 2.85pt;text-align: justify;"><span style=""> <span style="color: rgb(0,0,0);"> <span style="line-height: 20.0px;"> <b> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;">Điều 6: Thông báo</span></span></b></span></span></span></p>

<p style="margin: 6.0pt 2.85pt;text-align: justify;"><span style=""> <span style="color: rgb(0,0,0);"> <span style="line-height: 20.0px;"> <b> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;">Điều 7: Luật điều chỉnh và giải quyết tranh chấp</span></span></b></span></span></span></p>

<ol>
	<li style="margin-top: 6.0pt;margin-right: 2.85pt;margin-bottom: 6.0pt;text-align: justify;"><span style="background: white;"> <span style="line-height: 150.0%;"> <span style=""> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">Điều khoản Sử dụng này và Các Văn Kiện Giao Dịch khác được điều chỉnh theo pháp luật Việt Nam.</span></span></span></span></span></span></li>
	<li style="margin-top: 6.0pt;margin-right: 2.85pt;margin-bottom: 6.0pt;text-align: justify;"><span style="background: white;"> <span style="line-height: 150.0%;"> <span style=""> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">Mọi tranh chấp phát sinh từ hoặc liên quan đến </span></span></span> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);">Điều khoản Sử dụng</span></span></span> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);"> này và Các Văn Kiện Giao Dịch khác sẽ được giải quyết tại Tòa án có thẩm quyền.</span></span></span></span></span></span></li>
</ol>

<p style="margin: 6.0pt 2.85pt;text-align: justify;"><span style=""> <span style="color: rgb(0,0,0);"> <span style="line-height: 20.0px;"> <b> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;">Điều 8: Các điều khoản khác</span></span></b></span></span></span></p>

<ol>
	<li style="margin-top: 6.0pt;margin-right: 2.85pt;margin-bottom: 6.0pt;text-align: justify;"><span style="line-height: 150.0%;"> <span style=""> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);"> <span style="background-color: white;"> <span style=""> <span style="">Nếu một trong Các Bên bị ảnh hưởng bởi bất kỳ sự kiện nào nằm ngoài sự kiểm soát của mình một cách hợp lý, bao gồm hỏa hoạn, cháy nổ, lũ lụt hoặc thiên tai; hành vi, quy định hoặc pháp lệnh của cơ quan có thẩm quyền; chiến tranh, khủng bố, biến động nhân quyền; đình công, tạm ngưng sản xuất hoặc bất ổn nhân sự; hoặc sự thiếu hụt các dịch vụ công cộng hay các hãng vận tải (“<strong>Sự Kiện Bất Khả Kháng</strong>”), thì Bên bị ảnh hưởng bởi Sự Kiện Bất Khả Kháng sẽ không phải chịu trách nhiệm liên quan đến Điều khoản Sử dụng này và Các Văn Kiện Giao Dịch khác trong phạm vi bị ảnh hưởng bởi Sự Kiện Bất Khả Kháng; với điều kiện Bên bị ảnh hưởng bởi Sự Kiện Bất Khả Kháng ngay lập tức phải thông báo bằng văn bản cho Bên còn lại (Bên không bị ảnh hưởng bởi Sự Kiện Bất Khả Kháng) biết tình hình của Sự Kiện Bất Khả Kháng và Bên bị ảnh hưởng bởi Sự Kiện Bất Khả Kháng thực hiện mọi nỗ lực hợp lý để loại bỏ ảnh hưởng của Sự Kiện Bất Khả Kháng đến Điều khoản Sử dụng này và Các Văn Kiện Giao Dịch khác ngay khi có thể và trong phạm vi thực hiện được. Nếu như bất kỳ Sự Kiện Bất Khả Kháng nào diễn ra liên tục trong khoảng thời gian hơn 30 (ba mười) ngày thì Bên không bị ảnh hưởng bởi Sự Kiện Bất Khả Kháng có thể chấm dứt Điều khoản Sử dụng này và/hoặc Các Văn Kiện Giao Dịch khác bằng việc gửi thông báo bằng văn bản cho Bên còn lại. Để làm rõ, các trường hợp hệ thống xử lý, hệ thống truyền tin, hệ thống điện bị trục trặc, gặp sự cố, bị tấn công hoặc vì bất kỳ lý do gì nằm ngoài khả năng kiểm soát của </span></span></span></span></span></span> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);"> <span style="background-color: white;"> <span style=""> <span style="">VNPost</span></span></span></span></span></span> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);"> <span style="background-color: white;"> <span style=""> <span style=""> mà không phải phát sinh do lỗi của </span></span></span></span></span></span> <span style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);"> <span style="background-color: white;"> <span style=""> <span style="">VNPost</span></span></span></span></span></span> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);"> <span style="background-color: white;"> <span style=""> <span style=""> cũng được xem là 1 Sự Kiện Bất Khả Kháng theo quy định tại Điều khoản Sử dụng này.</span></span></span></span></span></span></span></span></li>
	<li style="margin-top: 6.0pt;margin-right: 2.85pt;margin-bottom: 6.0pt;text-align: justify;"><span style="line-height: 150.0%;"> <span style=""> <span lang="VI" style="font-size: 13.0pt;"> <span style="line-height: 26.0px;"> <span style="color: rgb(33,37,41);"> <span style="background-color: white;"> <span style=""> <span style="">Trường hợp có bất kỳ điều khoản nào của Điều khoản Sử dụng này và Các Văn Kiện Giao Dịch khác được tuyên là vô hiệu hoặc không thể thi hành, thì trong phạm vi điều khoản đó vô hiệu hoặc không thể thi hành, điều khoản đó được xem là không được đưa vào trong Điều khoản Sử dụng này và Các Văn Kiện Giao Dịch khác. Điều này không làm vô hiệu bất kỳ điều khoản nào còn lại của Điều khoản Sử dụng này và Các Văn Kiện Giao Dịch khác.</span></span></span></span></span></span></span></span></li>
</ol>
