/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package dtt.vn.user.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DataImport service. Represents a row in the &quot;idm_dataimport&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>dtt.vn.user.service.model.impl.DataImportModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>dtt.vn.user.service.model.impl.DataImportImpl</code>.
 * </p>
 *
 * @author nhanvienDTT
 * @see DataImport
 * @generated
 */
@ProviderType
public interface DataImportModel extends BaseModel<DataImport> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a data import model instance should use the {@link DataImport} interface instead.
	 */

	/**
	 * Returns the primary key of this data import.
	 *
	 * @return the primary key of this data import
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this data import.
	 *
	 * @param primaryKey the primary key of this data import
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this data import.
	 *
	 * @return the ID of this data import
	 */
	public long getId();

	/**
	 * Sets the ID of this data import.
	 *
	 * @param id the ID of this data import
	 */
	public void setId(long id);

	/**
	 * Returns the screen name of this data import.
	 *
	 * @return the screen name of this data import
	 */
	@AutoEscape
	public String getScreenName();

	/**
	 * Sets the screen name of this data import.
	 *
	 * @param screenName the screen name of this data import
	 */
	public void setScreenName(String screenName);

	/**
	 * Returns the first name of this data import.
	 *
	 * @return the first name of this data import
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this data import.
	 *
	 * @param firstName the first name of this data import
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this data import.
	 *
	 * @return the last name of this data import
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this data import.
	 *
	 * @param lastName the last name of this data import
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the unit of this data import.
	 *
	 * @return the unit of this data import
	 */
	@AutoEscape
	public String getUnit();

	/**
	 * Sets the unit of this data import.
	 *
	 * @param unit the unit of this data import
	 */
	public void setUnit(String unit);

	/**
	 * Returns the email address of this data import.
	 *
	 * @return the email address of this data import
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this data import.
	 *
	 * @param emailAddress the email address of this data import
	 */
	public void setEmailAddress(String emailAddress);

	/**
	 * Returns the phone of this data import.
	 *
	 * @return the phone of this data import
	 */
	@AutoEscape
	public String getPhone();

	/**
	 * Sets the phone of this data import.
	 *
	 * @param phone the phone of this data import
	 */
	public void setPhone(String phone);

	/**
	 * Returns the job title of this data import.
	 *
	 * @return the job title of this data import
	 */
	@AutoEscape
	public String getJobTitle();

	/**
	 * Sets the job title of this data import.
	 *
	 * @param jobTitle the job title of this data import
	 */
	public void setJobTitle(String jobTitle);

	/**
	 * Returns the name role of this data import.
	 *
	 * @return the name role of this data import
	 */
	@AutoEscape
	public String getNameRole();

	/**
	 * Sets the name role of this data import.
	 *
	 * @param nameRole the name role of this data import
	 */
	public void setNameRole(String nameRole);

	/**
	 * Returns the number ID of this data import.
	 *
	 * @return the number ID of this data import
	 */
	@AutoEscape
	public String getNumberId();

	/**
	 * Sets the number ID of this data import.
	 *
	 * @param numberId the number ID of this data import
	 */
	public void setNumberId(String numberId);

	/**
	 * Returns the has import of this data import.
	 *
	 * @return the has import of this data import
	 */
	@AutoEscape
	public String getHasImport();

	/**
	 * Sets the has import of this data import.
	 *
	 * @param hasImport the has import of this data import
	 */
	public void setHasImport(String hasImport);

	/**
	 * Returns the error msg of this data import.
	 *
	 * @return the error msg of this data import
	 */
	@AutoEscape
	public String getErrorMsg();

	/**
	 * Sets the error msg of this data import.
	 *
	 * @param errorMsg the error msg of this data import
	 */
	public void setErrorMsg(String errorMsg);

	/**
	 * Returns the insert date of this data import.
	 *
	 * @return the insert date of this data import
	 */
	public Date getInsertDate();

	/**
	 * Sets the insert date of this data import.
	 *
	 * @param insertDate the insert date of this data import
	 */
	public void setInsertDate(Date insertDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(dtt.vn.user.service.model.DataImport dataImport);

	@Override
	public int hashCode();

	@Override
	public CacheModel<dtt.vn.user.service.model.DataImport> toCacheModel();

	@Override
	public dtt.vn.user.service.model.DataImport toEscapedModel();

	@Override
	public dtt.vn.user.service.model.DataImport toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}