/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package dtt.vn.user.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the DoiTuongSuDung service. Represents a row in the &quot;ttnd_doituongsudung&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>dtt.vn.user.service.model.impl.DoiTuongSuDungModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>dtt.vn.user.service.model.impl.DoiTuongSuDungImpl</code>.
 * </p>
 *
 * @author nhanvienDTT
 * @see DoiTuongSuDung
 * @generated
 */
@ProviderType
public interface DoiTuongSuDungModel extends BaseModel<DoiTuongSuDung> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a doi tuong su dung model instance should use the {@link DoiTuongSuDung} interface instead.
	 */

	/**
	 * Returns the primary key of this doi tuong su dung.
	 *
	 * @return the primary key of this doi tuong su dung
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this doi tuong su dung.
	 *
	 * @param primaryKey the primary key of this doi tuong su dung
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this doi tuong su dung.
	 *
	 * @return the ID of this doi tuong su dung
	 */
	public long getId();

	/**
	 * Sets the ID of this doi tuong su dung.
	 *
	 * @param id the ID of this doi tuong su dung
	 */
	public void setId(long id);

	/**
	 * Returns the ma of this doi tuong su dung.
	 *
	 * @return the ma of this doi tuong su dung
	 */
	@AutoEscape
	public String getMa();

	/**
	 * Sets the ma of this doi tuong su dung.
	 *
	 * @param ma the ma of this doi tuong su dung
	 */
	public void setMa(String ma);

	/**
	 * Returns the ten of this doi tuong su dung.
	 *
	 * @return the ten of this doi tuong su dung
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this doi tuong su dung.
	 *
	 * @param ten the ten of this doi tuong su dung
	 */
	public void setTen(String ten);

	/**
	 * Returns the loai of this doi tuong su dung.
	 *
	 * @return the loai of this doi tuong su dung
	 */
	public int getLoai();

	/**
	 * Sets the loai of this doi tuong su dung.
	 *
	 * @param loai the loai of this doi tuong su dung
	 */
	public void setLoai(int loai);

	/**
	 * Returns the mo ta of this doi tuong su dung.
	 *
	 * @return the mo ta of this doi tuong su dung
	 */
	@AutoEscape
	public String getMoTa();

	/**
	 * Sets the mo ta of this doi tuong su dung.
	 *
	 * @param moTa the mo ta of this doi tuong su dung
	 */
	public void setMoTa(String moTa);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		dtt.vn.user.service.model.DoiTuongSuDung doiTuongSuDung);

	@Override
	public int hashCode();

	@Override
	public CacheModel<dtt.vn.user.service.model.DoiTuongSuDung> toCacheModel();

	@Override
	public dtt.vn.user.service.model.DoiTuongSuDung toEscapedModel();

	@Override
	public dtt.vn.user.service.model.DoiTuongSuDung toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}