/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package dtt.vn.user.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the ThongTinCanBo service. Represents a row in the &quot;ttnd_thongtincanbo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>dtt.vn.user.service.model.impl.ThongTinCanBoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>dtt.vn.user.service.model.impl.ThongTinCanBoImpl</code>.
 * </p>
 *
 * @author nhanvienDTT
 * @see ThongTinCanBo
 * @generated
 */
@ProviderType
public interface ThongTinCanBoModel extends BaseModel<ThongTinCanBo> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a thong tin can bo model instance should use the {@link ThongTinCanBo} interface instead.
	 */

	/**
	 * Returns the primary key of this thong tin can bo.
	 *
	 * @return the primary key of this thong tin can bo
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this thong tin can bo.
	 *
	 * @param primaryKey the primary key of this thong tin can bo
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this thong tin can bo.
	 *
	 * @return the ID of this thong tin can bo
	 */
	public long getId();

	/**
	 * Sets the ID of this thong tin can bo.
	 *
	 * @param id the ID of this thong tin can bo
	 */
	public void setId(long id);

	/**
	 * Returns the email address of this thong tin can bo.
	 *
	 * @return the email address of this thong tin can bo
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this thong tin can bo.
	 *
	 * @param emailAddress the email address of this thong tin can bo
	 */
	public void setEmailAddress(String emailAddress);

	/**
	 * Returns the user name of this thong tin can bo.
	 *
	 * @return the user name of this thong tin can bo
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this thong tin can bo.
	 *
	 * @param userName the user name of this thong tin can bo
	 */
	public void setUserName(String userName);

	/**
	 * Returns the name role of this thong tin can bo.
	 *
	 * @return the name role of this thong tin can bo
	 */
	@AutoEscape
	public String getNameRole();

	/**
	 * Sets the name role of this thong tin can bo.
	 *
	 * @param nameRole the name role of this thong tin can bo
	 */
	public void setNameRole(String nameRole);

	/**
	 * Returns the noi dung of this thong tin can bo.
	 *
	 * @return the noi dung of this thong tin can bo
	 */
	@AutoEscape
	public String getNoiDung();

	/**
	 * Sets the noi dung of this thong tin can bo.
	 *
	 * @param noiDung the noi dung of this thong tin can bo
	 */
	public void setNoiDung(String noiDung);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(dtt.vn.user.service.model.ThongTinCanBo thongTinCanBo);

	@Override
	public int hashCode();

	@Override
	public CacheModel<dtt.vn.user.service.model.ThongTinCanBo> toCacheModel();

	@Override
	public dtt.vn.user.service.model.ThongTinCanBo toEscapedModel();

	@Override
	public dtt.vn.user.service.model.ThongTinCanBo toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}