/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.core.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Mail service. Represents a row in the &quot;oep_mail_history&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>org.oep.core.model.impl.MailModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>org.oep.core.model.impl.MailImpl</code>.
 * </p>
 *
 * @author manhlb
 * @see Mail
 * @generated
 */
@ProviderType
public interface MailModel extends BaseModel<Mail> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a mail model instance should use the {@link Mail} interface instead.
	 */

	/**
	 * Returns the primary key of this mail.
	 *
	 * @return the primary key of this mail
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this mail.
	 *
	 * @param primaryKey the primary key of this mail
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this mail.
	 *
	 * @return the ID of this mail
	 */
	public long getId();

	/**
	 * Sets the ID of this mail.
	 *
	 * @param id the ID of this mail
	 */
	public void setId(long id);

	/**
	 * Returns the group ID of this mail.
	 *
	 * @return the group ID of this mail
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this mail.
	 *
	 * @param groupId the group ID of this mail
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the code of this mail.
	 *
	 * @return the code of this mail
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this mail.
	 *
	 * @param code the code of this mail
	 */
	public void setCode(String code);

	/**
	 * Returns the to address of this mail.
	 *
	 * @return the to address of this mail
	 */
	@AutoEscape
	public String getToAddress();

	/**
	 * Sets the to address of this mail.
	 *
	 * @param toAddress the to address of this mail
	 */
	public void setToAddress(String toAddress);

	/**
	 * Returns the subject of this mail.
	 *
	 * @return the subject of this mail
	 */
	@AutoEscape
	public String getSubject();

	/**
	 * Sets the subject of this mail.
	 *
	 * @param subject the subject of this mail
	 */
	public void setSubject(String subject);

	/**
	 * Returns the body of this mail.
	 *
	 * @return the body of this mail
	 */
	@AutoEscape
	public String getBody();

	/**
	 * Sets the body of this mail.
	 *
	 * @param body the body of this mail
	 */
	public void setBody(String body);

	/**
	 * Returns the ngay gui of this mail.
	 *
	 * @return the ngay gui of this mail
	 */
	public Date getNgayGui();

	/**
	 * Sets the ngay gui of this mail.
	 *
	 * @param ngayGui the ngay gui of this mail
	 */
	public void setNgayGui(Date ngayGui);

	/**
	 * Returns the trang thai of this mail.
	 *
	 * @return the trang thai of this mail
	 */
	public boolean getTrangThai();

	/**
	 * Returns <code>true</code> if this mail is trang thai.
	 *
	 * @return <code>true</code> if this mail is trang thai; <code>false</code> otherwise
	 */
	public boolean isTrangThai();

	/**
	 * Sets whether this mail is trang thai.
	 *
	 * @param trangThai the trang thai of this mail
	 */
	public void setTrangThai(boolean trangThai);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Mail mail);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Mail> toCacheModel();

	@Override
	public Mail toEscapedModel();

	@Override
	public Mail toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}