/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.core.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the MappingVmap service. Represents a row in the &quot;idm_mappingvmap&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>org.oep.core.model.impl.MappingVmapModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>org.oep.core.model.impl.MappingVmapImpl</code>.
 * </p>
 *
 * @author manhlb
 * @see MappingVmap
 * @generated
 */
@ProviderType
public interface MappingVmapModel extends BaseModel<MappingVmap> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a mapping vmap model instance should use the {@link MappingVmap} interface instead.
	 */

	/**
	 * Returns the primary key of this mapping vmap.
	 *
	 * @return the primary key of this mapping vmap
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this mapping vmap.
	 *
	 * @param primaryKey the primary key of this mapping vmap
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this mapping vmap.
	 *
	 * @return the ID of this mapping vmap
	 */
	public long getId();

	/**
	 * Sets the ID of this mapping vmap.
	 *
	 * @param id the ID of this mapping vmap
	 */
	public void setId(long id);

	/**
	 * Returns the classpk of this mapping vmap.
	 *
	 * @return the classpk of this mapping vmap
	 */
	public long getClasspk();

	/**
	 * Sets the classpk of this mapping vmap.
	 *
	 * @param classpk the classpk of this mapping vmap
	 */
	public void setClasspk(long classpk);

	/**
	 * Returns the classname of this mapping vmap.
	 *
	 * @return the classname of this mapping vmap
	 */
	@AutoEscape
	public String getClassname();

	/**
	 * Sets the classname of this mapping vmap.
	 *
	 * @param classname the classname of this mapping vmap
	 */
	public void setClassname(String classname);

	/**
	 * Returns the latitude of this mapping vmap.
	 *
	 * @return the latitude of this mapping vmap
	 */
	@AutoEscape
	public String getLatitude();

	/**
	 * Sets the latitude of this mapping vmap.
	 *
	 * @param latitude the latitude of this mapping vmap
	 */
	public void setLatitude(String latitude);

	/**
	 * Returns the longitude of this mapping vmap.
	 *
	 * @return the longitude of this mapping vmap
	 */
	@AutoEscape
	public String getLongitude();

	/**
	 * Sets the longitude of this mapping vmap.
	 *
	 * @param longitude the longitude of this mapping vmap
	 */
	public void setLongitude(String longitude);

	/**
	 * Returns the ghichu of this mapping vmap.
	 *
	 * @return the ghichu of this mapping vmap
	 */
	@AutoEscape
	public String getGhichu();

	/**
	 * Sets the ghichu of this mapping vmap.
	 *
	 * @param ghichu the ghichu of this mapping vmap
	 */
	public void setGhichu(String ghichu);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(MappingVmap mappingVmap);

	@Override
	public int hashCode();

	@Override
	public CacheModel<MappingVmap> toCacheModel();

	@Override
	public MappingVmap toEscapedModel();

	@Override
	public MappingVmap toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}