/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.core.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the PhanQuyen service. Represents a row in the &quot;idm_phanquyen&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>org.oep.core.model.impl.PhanQuyenModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>org.oep.core.model.impl.PhanQuyenImpl</code>.
 * </p>
 *
 * @author manhlb
 * @see PhanQuyen
 * @generated
 */
@ProviderType
public interface PhanQuyenModel extends BaseModel<PhanQuyen> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a phan quyen model instance should use the {@link PhanQuyen} interface instead.
	 */

	/**
	 * Returns the primary key of this phan quyen.
	 *
	 * @return the primary key of this phan quyen
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this phan quyen.
	 *
	 * @param primaryKey the primary key of this phan quyen
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this phan quyen.
	 *
	 * @return the ID of this phan quyen
	 */
	public long getId();

	/**
	 * Sets the ID of this phan quyen.
	 *
	 * @param id the ID of this phan quyen
	 */
	public void setId(long id);

	/**
	 * Returns the classname of this phan quyen.
	 *
	 * @return the classname of this phan quyen
	 */
	@AutoEscape
	public String getClassname();

	/**
	 * Sets the classname of this phan quyen.
	 *
	 * @param classname the classname of this phan quyen
	 */
	public void setClassname(String classname);

	/**
	 * Returns the classpk of this phan quyen.
	 *
	 * @return the classpk of this phan quyen
	 */
	public long getClasspk();

	/**
	 * Sets the classpk of this phan quyen.
	 *
	 * @param classpk the classpk of this phan quyen
	 */
	public void setClasspk(long classpk);

	/**
	 * Returns the giatri of this phan quyen.
	 *
	 * @return the giatri of this phan quyen
	 */
	@AutoEscape
	public String getGiatri();

	/**
	 * Sets the giatri of this phan quyen.
	 *
	 * @param giatri the giatri of this phan quyen
	 */
	public void setGiatri(String giatri);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PhanQuyen phanQuyen);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PhanQuyen> toCacheModel();

	@Override
	public PhanQuyen toEscapedModel();

	@Override
	public PhanQuyen toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}