/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.core.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the ThamSo service. Represents a row in the &quot;oep_thamso&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>org.oep.core.model.impl.ThamSoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>org.oep.core.model.impl.ThamSoImpl</code>.
 * </p>
 *
 * @author manhlb
 * @see ThamSo
 * @generated
 */
@ProviderType
public interface ThamSoModel extends BaseModel<ThamSo> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tham so model instance should use the {@link ThamSo} interface instead.
	 */

	/**
	 * Returns the primary key of this tham so.
	 *
	 * @return the primary key of this tham so
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tham so.
	 *
	 * @param primaryKey the primary key of this tham so
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this tham so.
	 *
	 * @return the ID of this tham so
	 */
	public long getId();

	/**
	 * Sets the ID of this tham so.
	 *
	 * @param id the ID of this tham so
	 */
	public void setId(long id);

	/**
	 * Returns the group ID of this tham so.
	 *
	 * @return the group ID of this tham so
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this tham so.
	 *
	 * @param groupId the group ID of this tham so
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the class name of this tham so.
	 *
	 * @return the class name of this tham so
	 */
	@AutoEscape
	public String getClassName();

	/**
	 * Sets the class name of this tham so.
	 *
	 * @param className the class name of this tham so
	 */
	public void setClassName(String className);

	/**
	 * Returns the class pk of this tham so.
	 *
	 * @return the class pk of this tham so
	 */
	public long getClassPK();

	/**
	 * Sets the class pk of this tham so.
	 *
	 * @param classPK the class pk of this tham so
	 */
	public void setClassPK(long classPK);

	/**
	 * Returns the loai ID of this tham so.
	 *
	 * @return the loai ID of this tham so
	 */
	public long getLoaiId();

	/**
	 * Sets the loai ID of this tham so.
	 *
	 * @param loaiId the loai ID of this tham so
	 */
	public void setLoaiId(long loaiId);

	/**
	 * Returns the ma of this tham so.
	 *
	 * @return the ma of this tham so
	 */
	@AutoEscape
	public String getMa();

	/**
	 * Sets the ma of this tham so.
	 *
	 * @param ma the ma of this tham so
	 */
	public void setMa(String ma);

	/**
	 * Returns the gia tri of this tham so.
	 *
	 * @return the gia tri of this tham so
	 */
	@AutoEscape
	public String getGiaTri();

	/**
	 * Sets the gia tri of this tham so.
	 *
	 * @param giaTri the gia tri of this tham so
	 */
	public void setGiaTri(String giaTri);

	/**
	 * Returns the mo ta of this tham so.
	 *
	 * @return the mo ta of this tham so
	 */
	@AutoEscape
	public String getMoTa();

	/**
	 * Sets the mo ta of this tham so.
	 *
	 * @param moTa the mo ta of this tham so
	 */
	public void setMoTa(String moTa);

	/**
	 * Returns the trang thai of this tham so.
	 *
	 * @return the trang thai of this tham so
	 */
	public boolean getTrangThai();

	/**
	 * Returns <code>true</code> if this tham so is trang thai.
	 *
	 * @return <code>true</code> if this tham so is trang thai; <code>false</code> otherwise
	 */
	public boolean isTrangThai();

	/**
	 * Sets whether this tham so is trang thai.
	 *
	 * @param trangThai the trang thai of this tham so
	 */
	public void setTrangThai(boolean trangThai);

	/**
	 * Returns the quyen tac dong of this tham so.
	 *
	 * @return the quyen tac dong of this tham so
	 */
	public int getQuyenTacDong();

	/**
	 * Sets the quyen tac dong of this tham so.
	 *
	 * @param quyenTacDong the quyen tac dong of this tham so
	 */
	public void setQuyenTacDong(int quyenTacDong);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ThamSo thamSo);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ThamSo> toCacheModel();

	@Override
	public ThamSo toEscapedModel();

	@Override
	public ThamSo toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}