/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.core.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the ThamSoLoai service. Represents a row in the &quot;oep_thamso_loai&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>org.oep.core.model.impl.ThamSoLoaiModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>org.oep.core.model.impl.ThamSoLoaiImpl</code>.
 * </p>
 *
 * @author manhlb
 * @see ThamSoLoai
 * @generated
 */
@ProviderType
public interface ThamSoLoaiModel extends BaseModel<ThamSoLoai> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tham so loai model instance should use the {@link ThamSoLoai} interface instead.
	 */

	/**
	 * Returns the primary key of this tham so loai.
	 *
	 * @return the primary key of this tham so loai
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tham so loai.
	 *
	 * @param primaryKey the primary key of this tham so loai
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this tham so loai.
	 *
	 * @return the ID of this tham so loai
	 */
	public long getId();

	/**
	 * Sets the ID of this tham so loai.
	 *
	 * @param id the ID of this tham so loai
	 */
	public void setId(long id);

	/**
	 * Returns the ma of this tham so loai.
	 *
	 * @return the ma of this tham so loai
	 */
	@AutoEscape
	public String getMa();

	/**
	 * Sets the ma of this tham so loai.
	 *
	 * @param ma the ma of this tham so loai
	 */
	public void setMa(String ma);

	/**
	 * Returns the ten of this tham so loai.
	 *
	 * @return the ten of this tham so loai
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this tham so loai.
	 *
	 * @param ten the ten of this tham so loai
	 */
	public void setTen(String ten);

	/**
	 * Returns the mo ta of this tham so loai.
	 *
	 * @return the mo ta of this tham so loai
	 */
	@AutoEscape
	public String getMoTa();

	/**
	 * Sets the mo ta of this tham so loai.
	 *
	 * @param moTa the mo ta of this tham so loai
	 */
	public void setMoTa(String moTa);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ThamSoLoai thamSoLoai);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ThamSoLoai> toCacheModel();

	@Override
	public ThamSoLoai toEscapedModel();

	@Override
	public ThamSoLoai toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}