/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.core.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the TrungTamHanhChinh service. Represents a row in the &quot;idm_trungtamhanhchinh&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>org.oep.core.model.impl.TrungTamHanhChinhModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>org.oep.core.model.impl.TrungTamHanhChinhImpl</code>.
 * </p>
 *
 * @author manhlb
 * @see TrungTamHanhChinh
 * @generated
 */
@ProviderType
public interface TrungTamHanhChinhModel extends BaseModel<TrungTamHanhChinh> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a trung tam hanh chinh model instance should use the {@link TrungTamHanhChinh} interface instead.
	 */

	/**
	 * Returns the primary key of this trung tam hanh chinh.
	 *
	 * @return the primary key of this trung tam hanh chinh
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this trung tam hanh chinh.
	 *
	 * @param primaryKey the primary key of this trung tam hanh chinh
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this trung tam hanh chinh.
	 *
	 * @return the ID of this trung tam hanh chinh
	 */
	public long getId();

	/**
	 * Sets the ID of this trung tam hanh chinh.
	 *
	 * @param id the ID of this trung tam hanh chinh
	 */
	public void setId(long id);

	/**
	 * Returns the ma of this trung tam hanh chinh.
	 *
	 * @return the ma of this trung tam hanh chinh
	 */
	@AutoEscape
	public String getMa();

	/**
	 * Sets the ma of this trung tam hanh chinh.
	 *
	 * @param ma the ma of this trung tam hanh chinh
	 */
	public void setMa(String ma);

	/**
	 * Returns the ten of this trung tam hanh chinh.
	 *
	 * @return the ten of this trung tam hanh chinh
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this trung tam hanh chinh.
	 *
	 * @param ten the ten of this trung tam hanh chinh
	 */
	public void setTen(String ten);

	/**
	 * Returns the don vi ID of this trung tam hanh chinh.
	 *
	 * @return the don vi ID of this trung tam hanh chinh
	 */
	public long getDonViId();

	/**
	 * Sets the don vi ID of this trung tam hanh chinh.
	 *
	 * @param donViId the don vi ID of this trung tam hanh chinh
	 */
	public void setDonViId(long donViId);

	/**
	 * Returns the don vi IDs of this trung tam hanh chinh.
	 *
	 * @return the don vi IDs of this trung tam hanh chinh
	 */
	@AutoEscape
	public String getDonViIds();

	/**
	 * Sets the don vi IDs of this trung tam hanh chinh.
	 *
	 * @param donViIds the don vi IDs of this trung tam hanh chinh
	 */
	public void setDonViIds(String donViIds);

	/**
	 * Returns the thong tin lien he of this trung tam hanh chinh.
	 *
	 * @return the thong tin lien he of this trung tam hanh chinh
	 */
	@AutoEscape
	public String getThongTinLienHe();

	/**
	 * Sets the thong tin lien he of this trung tam hanh chinh.
	 *
	 * @param thongTinLienHe the thong tin lien he of this trung tam hanh chinh
	 */
	public void setThongTinLienHe(String thongTinLienHe);

	/**
	 * Returns the trang thai of this trung tam hanh chinh.
	 *
	 * @return the trang thai of this trung tam hanh chinh
	 */
	public int getTrangThai();

	/**
	 * Sets the trang thai of this trung tam hanh chinh.
	 *
	 * @param trangThai the trang thai of this trung tam hanh chinh
	 */
	public void setTrangThai(int trangThai);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TrungTamHanhChinh trungTamHanhChinh);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TrungTamHanhChinh> toCacheModel();

	@Override
	public TrungTamHanhChinh toEscapedModel();

	@Override
	public TrungTamHanhChinh toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}