/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.danhmuc.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Nhom service. Represents a row in the &quot;data_group&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>org.oep.danhmuc.model.impl.NhomModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>org.oep.danhmuc.model.impl.NhomImpl</code>.
 * </p>
 *
 * @author nhanvienDTT
 * @see Nhom
 * @generated
 */
@ProviderType
public interface NhomModel extends BaseModel<Nhom> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a nhom model instance should use the {@link Nhom} interface instead.
	 */

	/**
	 * Returns the primary key of this nhom.
	 *
	 * @return the primary key of this nhom
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this nhom.
	 *
	 * @param primaryKey the primary key of this nhom
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this nhom.
	 *
	 * @return the ID of this nhom
	 */
	public long getId();

	/**
	 * Sets the ID of this nhom.
	 *
	 * @param id the ID of this nhom
	 */
	public void setId(long id);

	/**
	 * Returns the ma of this nhom.
	 *
	 * @return the ma of this nhom
	 */
	@AutoEscape
	public String getMa();

	/**
	 * Sets the ma of this nhom.
	 *
	 * @param ma the ma of this nhom
	 */
	public void setMa(String ma);

	/**
	 * Returns the ten of this nhom.
	 *
	 * @return the ten of this nhom
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this nhom.
	 *
	 * @param ten the ten of this nhom
	 */
	public void setTen(String ten);

	/**
	 * Returns the mota of this nhom.
	 *
	 * @return the mota of this nhom
	 */
	@AutoEscape
	public String getMota();

	/**
	 * Sets the mota of this nhom.
	 *
	 * @param mota the mota of this nhom
	 */
	public void setMota(String mota);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Nhom nhom);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Nhom> toCacheModel();

	@Override
	public Nhom toEscapedModel();

	@Override
	public Nhom toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}