/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package dtt.vn.vnpost.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the DanhMuc service. Represents a row in the &quot;data_item&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>dtt.vn.vnpost.model.impl.DanhMucModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>dtt.vn.vnpost.model.impl.DanhMucImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DanhMuc
 * @generated
 */
@ProviderType
public interface DanhMucModel extends BaseModel<DanhMuc> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a danh muc model instance should use the {@link DanhMuc} interface instead.
	 */

	/**
	 * Returns the primary key of this danh muc.
	 *
	 * @return the primary key of this danh muc
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this danh muc.
	 *
	 * @param primaryKey the primary key of this danh muc
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this danh muc.
	 *
	 * @return the ID of this danh muc
	 */
	public long getId();

	/**
	 * Sets the ID of this danh muc.
	 *
	 * @param id the ID of this danh muc
	 */
	public void setId(long id);

	/**
	 * Returns the nhom ID of this danh muc.
	 *
	 * @return the nhom ID of this danh muc
	 */
	public long getNhomId();

	/**
	 * Sets the nhom ID of this danh muc.
	 *
	 * @param nhomId the nhom ID of this danh muc
	 */
	public void setNhomId(long nhomId);

	/**
	 * Returns the ma of this danh muc.
	 *
	 * @return the ma of this danh muc
	 */
	@AutoEscape
	public String getMa();

	/**
	 * Sets the ma of this danh muc.
	 *
	 * @param ma the ma of this danh muc
	 */
	public void setMa(String ma);

	/**
	 * Returns the ten of this danh muc.
	 *
	 * @return the ten of this danh muc
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this danh muc.
	 *
	 * @param ten the ten of this danh muc
	 */
	public void setTen(String ten);

	/**
	 * Returns the mo ta of this danh muc.
	 *
	 * @return the mo ta of this danh muc
	 */
	@AutoEscape
	public String getMoTa();

	/**
	 * Sets the mo ta of this danh muc.
	 *
	 * @param moTa the mo ta of this danh muc
	 */
	public void setMoTa(String moTa);

	/**
	 * Returns the muc of this danh muc.
	 *
	 * @return the muc of this danh muc
	 */
	public int getMuc();

	/**
	 * Sets the muc of this danh muc.
	 *
	 * @param muc the muc of this danh muc
	 */
	public void setMuc(int muc);

	/**
	 * Returns the cha ID of this danh muc.
	 *
	 * @return the cha ID of this danh muc
	 */
	public long getChaId();

	/**
	 * Sets the cha ID of this danh muc.
	 *
	 * @param chaId the cha ID of this danh muc
	 */
	public void setChaId(long chaId);

	/**
	 * Returns the thu tu hien thi of this danh muc.
	 *
	 * @return the thu tu hien thi of this danh muc
	 */
	public int getThuTuHienThi();

	/**
	 * Sets the thu tu hien thi of this danh muc.
	 *
	 * @param thuTuHienThi the thu tu hien thi of this danh muc
	 */
	public void setThuTuHienThi(int thuTuHienThi);

	/**
	 * Returns the ma gia pha of this danh muc.
	 *
	 * @return the ma gia pha of this danh muc
	 */
	@AutoEscape
	public String getMaGiaPha();

	/**
	 * Sets the ma gia pha of this danh muc.
	 *
	 * @param maGiaPha the ma gia pha of this danh muc
	 */
	public void setMaGiaPha(String maGiaPha);

	/**
	 * Returns the trang thai of this danh muc.
	 *
	 * @return the trang thai of this danh muc
	 */
	public boolean getTrangThai();

	/**
	 * Returns <code>true</code> if this danh muc is trang thai.
	 *
	 * @return <code>true</code> if this danh muc is trang thai; <code>false</code> otherwise
	 */
	public boolean isTrangThai();

	/**
	 * Sets whether this danh muc is trang thai.
	 *
	 * @param trangThai the trang thai of this danh muc
	 */
	public void setTrangThai(boolean trangThai);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(dtt.vn.vnpost.model.DanhMuc danhMuc);

	@Override
	public int hashCode();

	@Override
	public CacheModel<dtt.vn.vnpost.model.DanhMuc> toCacheModel();

	@Override
	public dtt.vn.vnpost.model.DanhMuc toEscapedModel();

	@Override
	public dtt.vn.vnpost.model.DanhMuc toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}