create table data_group (
	id LONG not null primary key,
	ma VARCHAR(75) null,
	ten VARCHAR(75) null,
	mota VARCHAR(75) null
);

create table data_item (
	id LONG not null primary key,
	nhom_id LONG,
	ma VARCHAR(75) null,
	ten VARCHAR(75) null,
	mota VARCHAR(75) null,
	muc INTEGER,
	cha_id LONG,
	thutu_hienthi INTEGER,
	ma_giapha VARCHAR(75) null,
	trangthai BOOLEAN
);

create table idm_Account (
	accountId LONG not null primary key,
	accountType INTEGER,
	accountName VARCHAR(75) null,
	companyId LONG,
	groupId LONG,
	userId LONG,
	createDate DATE null,
	modifiedDate DATE null,
	fullName VARCHAR(75) null,
	birthdate DATE null,
	email VARCHAR(75) null,
	telNo VARCHAR(75) null,
	personalId VARCHAR(75) null,
	address VARCHAR(75) null,
	gender INTEGER,
	legalDelegate VARCHAR(75) null,
	taxCode VARCHAR(75) null,
	insuranceCode VARCHAR(75) null,
	nationality VARCHAR(75) null,
	ethnicGroup VARCHAR(75) null,
	familyRegNo VARCHAR(75) null,
	maritalStatus INTEGER,
	workingPlace VARCHAR(75) null,
	nativePlace VARCHAR(75) null,
	rangeDate DATE null,
	issuedBy VARCHAR(75) null,
	fatherName VARCHAR(75) null,
	motherName VARCHAR(75) null,
	guardianName VARCHAR(75) null,
	spouseName VARCHAR(75) null,
	headHouseholdName VARCHAR(75) null,
	nation VARCHAR(75) null,
	representativeNumber VARCHAR(75) null,
	representativeName VARCHAR(75) null,
	representativeTelNo VARCHAR(75) null,
	fax VARCHAR(75) null,
	superiorOrganization VARCHAR(75) null,
	note VARCHAR(75) null,
	idDBXM LONG,
	cityCode VARCHAR(75) null,
	districtCode VARCHAR(75) null,
	wardCode VARCHAR(75) null,
	cityCodeXM VARCHAR(75) null,
	districtCodeXM VARCHAR(75) null,
	wardCodeXM VARCHAR(75) null,
	addressXM VARCHAR(75) null,
	attachFile LONG,
	accountStatus INTEGER,
	processStatus INTEGER,
	signImageId LONG,
	hoSoId LONG,
	message VARCHAR(75) null,
	assignUserId LONG,
	ipLevel INTEGER,
	reOpen BOOLEAN
);

create table idm_photo (
	imageId LONG not null primary key,
	className VARCHAR(75) null,
	classPK LONG,
	description VARCHAR(75) null,
	thumbnailId LONG,
	imageType INTEGER,
	contentType VARCHAR(75) null,
	approved BOOLEAN,
	uploadDate DATE null,
	message VARCHAR(75) null
);

create table idm_workitem (
	workItemId LONG not null primary key,
	groupId LONG,
	userId LONG,
	createDate DATE null,
	modifiedDate DATE null,
	title VARCHAR(75) null,
	status VARCHAR(75) null,
	statusResponse VARCHAR(75) null,
	startTime DATE null,
	endTime DATE null,
	accountId LONG
);