/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.core.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.oep.core.model.PhanQuyen;
import org.oep.core.model.PhanQuyenModel;

/**
 * The base model implementation for the PhanQuyen service. Represents a row in the &quot;idm_phanquyen&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>PhanQuyenModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PhanQuyenImpl}.
 * </p>
 *
 * @author manhlb
 * @see PhanQuyenImpl
 * @generated
 */
@ProviderType
public class PhanQuyenModelImpl
	extends BaseModelImpl<PhanQuyen> implements PhanQuyenModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a phan quyen model instance should use the <code>PhanQuyen</code> interface instead.
	 */
	public static final String TABLE_NAME = "idm_phanquyen";

	public static final Object[][] TABLE_COLUMNS = {
		{"id", Types.BIGINT}, {"classname", Types.VARCHAR},
		{"classpk", Types.BIGINT}, {"giatri", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classname", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("classpk", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("giatri", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table idm_phanquyen (id LONG not null primary key,classname VARCHAR(75) null,classpk LONG,giatri VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table idm_phanquyen";

	public static final String ORDER_BY_JPQL = " ORDER BY phanQuyen.id DESC";

	public static final String ORDER_BY_SQL = " ORDER BY idm_phanquyen.id DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		org.oep.core.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.org.oep.core.model.PhanQuyen"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		org.oep.core.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.org.oep.core.model.PhanQuyen"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		org.oep.core.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.org.oep.core.model.PhanQuyen"),
		true);

	public static final long CLASSNAME_COLUMN_BITMASK = 1L;

	public static final long CLASSPK_COLUMN_BITMASK = 2L;

	public static final long ID_COLUMN_BITMASK = 4L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		org.oep.core.service.util.ServiceProps.get(
			"lock.expiration.time.org.oep.core.model.PhanQuyen"));

	public PhanQuyenModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PhanQuyen.class;
	}

	@Override
	public String getModelClassName() {
		return PhanQuyen.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<PhanQuyen, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<PhanQuyen, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PhanQuyen, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((PhanQuyen)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<PhanQuyen, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<PhanQuyen, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(PhanQuyen)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<PhanQuyen, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<PhanQuyen, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, PhanQuyen>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			PhanQuyen.class.getClassLoader(), PhanQuyen.class,
			ModelWrapper.class);

		try {
			Constructor<PhanQuyen> constructor =
				(Constructor<PhanQuyen>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<PhanQuyen, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<PhanQuyen, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<PhanQuyen, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<PhanQuyen, Object>>();
		Map<String, BiConsumer<PhanQuyen, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<PhanQuyen, ?>>();

		attributeGetterFunctions.put(
			"id",
			new Function<PhanQuyen, Object>() {

				@Override
				public Object apply(PhanQuyen phanQuyen) {
					return phanQuyen.getId();
				}

			});
		attributeSetterBiConsumers.put(
			"id",
			new BiConsumer<PhanQuyen, Object>() {

				@Override
				public void accept(PhanQuyen phanQuyen, Object id) {
					phanQuyen.setId((Long)id);
				}

			});
		attributeGetterFunctions.put(
			"classname",
			new Function<PhanQuyen, Object>() {

				@Override
				public Object apply(PhanQuyen phanQuyen) {
					return phanQuyen.getClassname();
				}

			});
		attributeSetterBiConsumers.put(
			"classname",
			new BiConsumer<PhanQuyen, Object>() {

				@Override
				public void accept(PhanQuyen phanQuyen, Object classname) {
					phanQuyen.setClassname((String)classname);
				}

			});
		attributeGetterFunctions.put(
			"classpk",
			new Function<PhanQuyen, Object>() {

				@Override
				public Object apply(PhanQuyen phanQuyen) {
					return phanQuyen.getClasspk();
				}

			});
		attributeSetterBiConsumers.put(
			"classpk",
			new BiConsumer<PhanQuyen, Object>() {

				@Override
				public void accept(PhanQuyen phanQuyen, Object classpk) {
					phanQuyen.setClasspk((Long)classpk);
				}

			});
		attributeGetterFunctions.put(
			"giatri",
			new Function<PhanQuyen, Object>() {

				@Override
				public Object apply(PhanQuyen phanQuyen) {
					return phanQuyen.getGiatri();
				}

			});
		attributeSetterBiConsumers.put(
			"giatri",
			new BiConsumer<PhanQuyen, Object>() {

				@Override
				public void accept(PhanQuyen phanQuyen, Object giatri) {
					phanQuyen.setGiatri((String)giatri);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	@Override
	public String getClassname() {
		if (_classname == null) {
			return "";
		}
		else {
			return _classname;
		}
	}

	@Override
	public void setClassname(String classname) {
		_columnBitmask |= CLASSNAME_COLUMN_BITMASK;

		if (_originalClassname == null) {
			_originalClassname = _classname;
		}

		_classname = classname;
	}

	public String getOriginalClassname() {
		return GetterUtil.getString(_originalClassname);
	}

	@Override
	public long getClasspk() {
		return _classpk;
	}

	@Override
	public void setClasspk(long classpk) {
		_columnBitmask |= CLASSPK_COLUMN_BITMASK;

		if (!_setOriginalClasspk) {
			_setOriginalClasspk = true;

			_originalClasspk = _classpk;
		}

		_classpk = classpk;
	}

	public long getOriginalClasspk() {
		return _originalClasspk;
	}

	@Override
	public String getGiatri() {
		if (_giatri == null) {
			return "";
		}
		else {
			return _giatri;
		}
	}

	@Override
	public void setGiatri(String giatri) {
		_giatri = giatri;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, PhanQuyen.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PhanQuyen toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = _escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PhanQuyenImpl phanQuyenImpl = new PhanQuyenImpl();

		phanQuyenImpl.setId(getId());
		phanQuyenImpl.setClassname(getClassname());
		phanQuyenImpl.setClasspk(getClasspk());
		phanQuyenImpl.setGiatri(getGiatri());

		phanQuyenImpl.resetOriginalValues();

		return phanQuyenImpl;
	}

	@Override
	public int compareTo(PhanQuyen phanQuyen) {
		int value = 0;

		if (getId() < phanQuyen.getId()) {
			value = -1;
		}
		else if (getId() > phanQuyen.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof PhanQuyen)) {
			return false;
		}

		PhanQuyen phanQuyen = (PhanQuyen)obj;

		long primaryKey = phanQuyen.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		PhanQuyenModelImpl phanQuyenModelImpl = this;

		phanQuyenModelImpl._originalClassname = phanQuyenModelImpl._classname;

		phanQuyenModelImpl._originalClasspk = phanQuyenModelImpl._classpk;

		phanQuyenModelImpl._setOriginalClasspk = false;

		phanQuyenModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<PhanQuyen> toCacheModel() {
		PhanQuyenCacheModel phanQuyenCacheModel = new PhanQuyenCacheModel();

		phanQuyenCacheModel.id = getId();

		phanQuyenCacheModel.classname = getClassname();

		String classname = phanQuyenCacheModel.classname;

		if ((classname != null) && (classname.length() == 0)) {
			phanQuyenCacheModel.classname = null;
		}

		phanQuyenCacheModel.classpk = getClasspk();

		phanQuyenCacheModel.giatri = getGiatri();

		String giatri = phanQuyenCacheModel.giatri;

		if ((giatri != null) && (giatri.length() == 0)) {
			phanQuyenCacheModel.giatri = null;
		}

		return phanQuyenCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<PhanQuyen, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<PhanQuyen, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PhanQuyen, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((PhanQuyen)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<PhanQuyen, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<PhanQuyen, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PhanQuyen, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((PhanQuyen)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final Function<InvocationHandler, PhanQuyen>
		_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	private long _id;
	private String _classname;
	private String _originalClassname;
	private long _classpk;
	private long _originalClasspk;
	private boolean _setOriginalClasspk;
	private String _giatri;
	private long _columnBitmask;
	private PhanQuyen _escapedModel;

}