/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.core.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.oep.core.model.ThamSoLoai;
import org.oep.core.model.ThamSoLoaiModel;

/**
 * The base model implementation for the ThamSoLoai service. Represents a row in the &quot;oep_thamso_loai&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>ThamSoLoaiModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ThamSoLoaiImpl}.
 * </p>
 *
 * @author manhlb
 * @see ThamSoLoaiImpl
 * @generated
 */
@ProviderType
public class ThamSoLoaiModelImpl
	extends BaseModelImpl<ThamSoLoai> implements ThamSoLoaiModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tham so loai model instance should use the <code>ThamSoLoai</code> interface instead.
	 */
	public static final String TABLE_NAME = "oep_thamso_loai";

	public static final Object[][] TABLE_COLUMNS = {
		{"id", Types.BIGINT}, {"ma", Types.VARCHAR}, {"ten", Types.VARCHAR},
		{"mota", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ma", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ten", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("mota", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table oep_thamso_loai (id LONG not null primary key,ma VARCHAR(75) null,ten VARCHAR(75) null,mota VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table oep_thamso_loai";

	public static final String ORDER_BY_JPQL = " ORDER BY thamSoLoai.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY oep_thamso_loai.id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		org.oep.core.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.org.oep.core.model.ThamSoLoai"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		org.oep.core.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.org.oep.core.model.ThamSoLoai"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		org.oep.core.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.org.oep.core.model.ThamSoLoai"),
		true);

	public static final long TEN_COLUMN_BITMASK = 1L;

	public static final long ID_COLUMN_BITMASK = 2L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		org.oep.core.service.util.ServiceProps.get(
			"lock.expiration.time.org.oep.core.model.ThamSoLoai"));

	public ThamSoLoaiModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ThamSoLoai.class;
	}

	@Override
	public String getModelClassName() {
		return ThamSoLoai.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ThamSoLoai, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ThamSoLoai, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ThamSoLoai, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((ThamSoLoai)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ThamSoLoai, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ThamSoLoai, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ThamSoLoai)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ThamSoLoai, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ThamSoLoai, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, ThamSoLoai>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			ThamSoLoai.class.getClassLoader(), ThamSoLoai.class,
			ModelWrapper.class);

		try {
			Constructor<ThamSoLoai> constructor =
				(Constructor<ThamSoLoai>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<ThamSoLoai, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ThamSoLoai, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ThamSoLoai, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<ThamSoLoai, Object>>();
		Map<String, BiConsumer<ThamSoLoai, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ThamSoLoai, ?>>();

		attributeGetterFunctions.put(
			"id",
			new Function<ThamSoLoai, Object>() {

				@Override
				public Object apply(ThamSoLoai thamSoLoai) {
					return thamSoLoai.getId();
				}

			});
		attributeSetterBiConsumers.put(
			"id",
			new BiConsumer<ThamSoLoai, Object>() {

				@Override
				public void accept(ThamSoLoai thamSoLoai, Object id) {
					thamSoLoai.setId((Long)id);
				}

			});
		attributeGetterFunctions.put(
			"ma",
			new Function<ThamSoLoai, Object>() {

				@Override
				public Object apply(ThamSoLoai thamSoLoai) {
					return thamSoLoai.getMa();
				}

			});
		attributeSetterBiConsumers.put(
			"ma",
			new BiConsumer<ThamSoLoai, Object>() {

				@Override
				public void accept(ThamSoLoai thamSoLoai, Object ma) {
					thamSoLoai.setMa((String)ma);
				}

			});
		attributeGetterFunctions.put(
			"ten",
			new Function<ThamSoLoai, Object>() {

				@Override
				public Object apply(ThamSoLoai thamSoLoai) {
					return thamSoLoai.getTen();
				}

			});
		attributeSetterBiConsumers.put(
			"ten",
			new BiConsumer<ThamSoLoai, Object>() {

				@Override
				public void accept(ThamSoLoai thamSoLoai, Object ten) {
					thamSoLoai.setTen((String)ten);
				}

			});
		attributeGetterFunctions.put(
			"moTa",
			new Function<ThamSoLoai, Object>() {

				@Override
				public Object apply(ThamSoLoai thamSoLoai) {
					return thamSoLoai.getMoTa();
				}

			});
		attributeSetterBiConsumers.put(
			"moTa",
			new BiConsumer<ThamSoLoai, Object>() {

				@Override
				public void accept(ThamSoLoai thamSoLoai, Object moTa) {
					thamSoLoai.setMoTa((String)moTa);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@Override
	public String getMa() {
		if (_ma == null) {
			return "";
		}
		else {
			return _ma;
		}
	}

	@Override
	public void setMa(String ma) {
		_ma = ma;
	}

	@Override
	public String getTen() {
		if (_ten == null) {
			return "";
		}
		else {
			return _ten;
		}
	}

	@Override
	public void setTen(String ten) {
		_columnBitmask |= TEN_COLUMN_BITMASK;

		if (_originalTen == null) {
			_originalTen = _ten;
		}

		_ten = ten;
	}

	public String getOriginalTen() {
		return GetterUtil.getString(_originalTen);
	}

	@Override
	public String getMoTa() {
		if (_moTa == null) {
			return "";
		}
		else {
			return _moTa;
		}
	}

	@Override
	public void setMoTa(String moTa) {
		_moTa = moTa;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, ThamSoLoai.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ThamSoLoai toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = _escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ThamSoLoaiImpl thamSoLoaiImpl = new ThamSoLoaiImpl();

		thamSoLoaiImpl.setId(getId());
		thamSoLoaiImpl.setMa(getMa());
		thamSoLoaiImpl.setTen(getTen());
		thamSoLoaiImpl.setMoTa(getMoTa());

		thamSoLoaiImpl.resetOriginalValues();

		return thamSoLoaiImpl;
	}

	@Override
	public int compareTo(ThamSoLoai thamSoLoai) {
		long primaryKey = thamSoLoai.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ThamSoLoai)) {
			return false;
		}

		ThamSoLoai thamSoLoai = (ThamSoLoai)obj;

		long primaryKey = thamSoLoai.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		ThamSoLoaiModelImpl thamSoLoaiModelImpl = this;

		thamSoLoaiModelImpl._originalTen = thamSoLoaiModelImpl._ten;

		thamSoLoaiModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ThamSoLoai> toCacheModel() {
		ThamSoLoaiCacheModel thamSoLoaiCacheModel = new ThamSoLoaiCacheModel();

		thamSoLoaiCacheModel.id = getId();

		thamSoLoaiCacheModel.ma = getMa();

		String ma = thamSoLoaiCacheModel.ma;

		if ((ma != null) && (ma.length() == 0)) {
			thamSoLoaiCacheModel.ma = null;
		}

		thamSoLoaiCacheModel.ten = getTen();

		String ten = thamSoLoaiCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			thamSoLoaiCacheModel.ten = null;
		}

		thamSoLoaiCacheModel.moTa = getMoTa();

		String moTa = thamSoLoaiCacheModel.moTa;

		if ((moTa != null) && (moTa.length() == 0)) {
			thamSoLoaiCacheModel.moTa = null;
		}

		return thamSoLoaiCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ThamSoLoai, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ThamSoLoai, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ThamSoLoai, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((ThamSoLoai)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ThamSoLoai, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ThamSoLoai, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ThamSoLoai, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ThamSoLoai)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final Function<InvocationHandler, ThamSoLoai>
		_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	private long _id;
	private String _ma;
	private String _ten;
	private String _originalTen;
	private String _moTa;
	private long _columnBitmask;
	private ThamSoLoai _escapedModel;

}