/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.oep.core.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import javax.sql.DataSource;

import org.oep.core.model.LogSMS;
import org.oep.core.service.LogSMSService;
import org.oep.core.service.persistence.LogSMSFinder;
import org.oep.core.service.persistence.LogSMSPersistence;
import org.oep.core.service.persistence.MailPersistence;
import org.oep.core.service.persistence.MappingVmapPersistence;
import org.oep.core.service.persistence.PhanQuyenPersistence;
import org.oep.core.service.persistence.ThamSoFinder;
import org.oep.core.service.persistence.ThamSoLoaiPersistence;
import org.oep.core.service.persistence.ThamSoPersistence;
import org.oep.core.service.persistence.TrungTamHanhChinhFinder;
import org.oep.core.service.persistence.TrungTamHanhChinhPersistence;

/**
 * Provides the base implementation for the log sms remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link org.oep.core.service.impl.LogSMSServiceImpl}.
 * </p>
 *
 * @author manhlb
 * @see org.oep.core.service.impl.LogSMSServiceImpl
 * @generated
 */
public abstract class LogSMSServiceBaseImpl
	extends BaseServiceImpl implements LogSMSService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>LogSMSService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>org.oep.core.service.LogSMSServiceUtil</code>.
	 */

	/**
	 * Returns the log sms local service.
	 *
	 * @return the log sms local service
	 */
	public org.oep.core.service.LogSMSLocalService getLogSMSLocalService() {
		return logSMSLocalService;
	}

	/**
	 * Sets the log sms local service.
	 *
	 * @param logSMSLocalService the log sms local service
	 */
	public void setLogSMSLocalService(
		org.oep.core.service.LogSMSLocalService logSMSLocalService) {

		this.logSMSLocalService = logSMSLocalService;
	}

	/**
	 * Returns the log sms remote service.
	 *
	 * @return the log sms remote service
	 */
	public LogSMSService getLogSMSService() {
		return logSMSService;
	}

	/**
	 * Sets the log sms remote service.
	 *
	 * @param logSMSService the log sms remote service
	 */
	public void setLogSMSService(LogSMSService logSMSService) {
		this.logSMSService = logSMSService;
	}

	/**
	 * Returns the log sms persistence.
	 *
	 * @return the log sms persistence
	 */
	public LogSMSPersistence getLogSMSPersistence() {
		return logSMSPersistence;
	}

	/**
	 * Sets the log sms persistence.
	 *
	 * @param logSMSPersistence the log sms persistence
	 */
	public void setLogSMSPersistence(LogSMSPersistence logSMSPersistence) {
		this.logSMSPersistence = logSMSPersistence;
	}

	/**
	 * Returns the log sms finder.
	 *
	 * @return the log sms finder
	 */
	public LogSMSFinder getLogSMSFinder() {
		return logSMSFinder;
	}

	/**
	 * Sets the log sms finder.
	 *
	 * @param logSMSFinder the log sms finder
	 */
	public void setLogSMSFinder(LogSMSFinder logSMSFinder) {
		this.logSMSFinder = logSMSFinder;
	}

	/**
	 * Returns the mail local service.
	 *
	 * @return the mail local service
	 */
	public org.oep.core.service.MailLocalService getMailLocalService() {
		return mailLocalService;
	}

	/**
	 * Sets the mail local service.
	 *
	 * @param mailLocalService the mail local service
	 */
	public void setMailLocalService(
		org.oep.core.service.MailLocalService mailLocalService) {

		this.mailLocalService = mailLocalService;
	}

	/**
	 * Returns the mail persistence.
	 *
	 * @return the mail persistence
	 */
	public MailPersistence getMailPersistence() {
		return mailPersistence;
	}

	/**
	 * Sets the mail persistence.
	 *
	 * @param mailPersistence the mail persistence
	 */
	public void setMailPersistence(MailPersistence mailPersistence) {
		this.mailPersistence = mailPersistence;
	}

	/**
	 * Returns the mapping vmap local service.
	 *
	 * @return the mapping vmap local service
	 */
	public org.oep.core.service.MappingVmapLocalService
		getMappingVmapLocalService() {

		return mappingVmapLocalService;
	}

	/**
	 * Sets the mapping vmap local service.
	 *
	 * @param mappingVmapLocalService the mapping vmap local service
	 */
	public void setMappingVmapLocalService(
		org.oep.core.service.MappingVmapLocalService mappingVmapLocalService) {

		this.mappingVmapLocalService = mappingVmapLocalService;
	}

	/**
	 * Returns the mapping vmap persistence.
	 *
	 * @return the mapping vmap persistence
	 */
	public MappingVmapPersistence getMappingVmapPersistence() {
		return mappingVmapPersistence;
	}

	/**
	 * Sets the mapping vmap persistence.
	 *
	 * @param mappingVmapPersistence the mapping vmap persistence
	 */
	public void setMappingVmapPersistence(
		MappingVmapPersistence mappingVmapPersistence) {

		this.mappingVmapPersistence = mappingVmapPersistence;
	}

	/**
	 * Returns the phan quyen local service.
	 *
	 * @return the phan quyen local service
	 */
	public org.oep.core.service.PhanQuyenLocalService
		getPhanQuyenLocalService() {

		return phanQuyenLocalService;
	}

	/**
	 * Sets the phan quyen local service.
	 *
	 * @param phanQuyenLocalService the phan quyen local service
	 */
	public void setPhanQuyenLocalService(
		org.oep.core.service.PhanQuyenLocalService phanQuyenLocalService) {

		this.phanQuyenLocalService = phanQuyenLocalService;
	}

	/**
	 * Returns the phan quyen persistence.
	 *
	 * @return the phan quyen persistence
	 */
	public PhanQuyenPersistence getPhanQuyenPersistence() {
		return phanQuyenPersistence;
	}

	/**
	 * Sets the phan quyen persistence.
	 *
	 * @param phanQuyenPersistence the phan quyen persistence
	 */
	public void setPhanQuyenPersistence(
		PhanQuyenPersistence phanQuyenPersistence) {

		this.phanQuyenPersistence = phanQuyenPersistence;
	}

	/**
	 * Returns the tham so local service.
	 *
	 * @return the tham so local service
	 */
	public org.oep.core.service.ThamSoLocalService getThamSoLocalService() {
		return thamSoLocalService;
	}

	/**
	 * Sets the tham so local service.
	 *
	 * @param thamSoLocalService the tham so local service
	 */
	public void setThamSoLocalService(
		org.oep.core.service.ThamSoLocalService thamSoLocalService) {

		this.thamSoLocalService = thamSoLocalService;
	}

	/**
	 * Returns the tham so persistence.
	 *
	 * @return the tham so persistence
	 */
	public ThamSoPersistence getThamSoPersistence() {
		return thamSoPersistence;
	}

	/**
	 * Sets the tham so persistence.
	 *
	 * @param thamSoPersistence the tham so persistence
	 */
	public void setThamSoPersistence(ThamSoPersistence thamSoPersistence) {
		this.thamSoPersistence = thamSoPersistence;
	}

	/**
	 * Returns the tham so finder.
	 *
	 * @return the tham so finder
	 */
	public ThamSoFinder getThamSoFinder() {
		return thamSoFinder;
	}

	/**
	 * Sets the tham so finder.
	 *
	 * @param thamSoFinder the tham so finder
	 */
	public void setThamSoFinder(ThamSoFinder thamSoFinder) {
		this.thamSoFinder = thamSoFinder;
	}

	/**
	 * Returns the tham so loai local service.
	 *
	 * @return the tham so loai local service
	 */
	public org.oep.core.service.ThamSoLoaiLocalService
		getThamSoLoaiLocalService() {

		return thamSoLoaiLocalService;
	}

	/**
	 * Sets the tham so loai local service.
	 *
	 * @param thamSoLoaiLocalService the tham so loai local service
	 */
	public void setThamSoLoaiLocalService(
		org.oep.core.service.ThamSoLoaiLocalService thamSoLoaiLocalService) {

		this.thamSoLoaiLocalService = thamSoLoaiLocalService;
	}

	/**
	 * Returns the tham so loai persistence.
	 *
	 * @return the tham so loai persistence
	 */
	public ThamSoLoaiPersistence getThamSoLoaiPersistence() {
		return thamSoLoaiPersistence;
	}

	/**
	 * Sets the tham so loai persistence.
	 *
	 * @param thamSoLoaiPersistence the tham so loai persistence
	 */
	public void setThamSoLoaiPersistence(
		ThamSoLoaiPersistence thamSoLoaiPersistence) {

		this.thamSoLoaiPersistence = thamSoLoaiPersistence;
	}

	/**
	 * Returns the trung tam hanh chinh local service.
	 *
	 * @return the trung tam hanh chinh local service
	 */
	public org.oep.core.service.TrungTamHanhChinhLocalService
		getTrungTamHanhChinhLocalService() {

		return trungTamHanhChinhLocalService;
	}

	/**
	 * Sets the trung tam hanh chinh local service.
	 *
	 * @param trungTamHanhChinhLocalService the trung tam hanh chinh local service
	 */
	public void setTrungTamHanhChinhLocalService(
		org.oep.core.service.TrungTamHanhChinhLocalService
			trungTamHanhChinhLocalService) {

		this.trungTamHanhChinhLocalService = trungTamHanhChinhLocalService;
	}

	/**
	 * Returns the trung tam hanh chinh persistence.
	 *
	 * @return the trung tam hanh chinh persistence
	 */
	public TrungTamHanhChinhPersistence getTrungTamHanhChinhPersistence() {
		return trungTamHanhChinhPersistence;
	}

	/**
	 * Sets the trung tam hanh chinh persistence.
	 *
	 * @param trungTamHanhChinhPersistence the trung tam hanh chinh persistence
	 */
	public void setTrungTamHanhChinhPersistence(
		TrungTamHanhChinhPersistence trungTamHanhChinhPersistence) {

		this.trungTamHanhChinhPersistence = trungTamHanhChinhPersistence;
	}

	/**
	 * Returns the trung tam hanh chinh finder.
	 *
	 * @return the trung tam hanh chinh finder
	 */
	public TrungTamHanhChinhFinder getTrungTamHanhChinhFinder() {
		return trungTamHanhChinhFinder;
	}

	/**
	 * Sets the trung tam hanh chinh finder.
	 *
	 * @param trungTamHanhChinhFinder the trung tam hanh chinh finder
	 */
	public void setTrungTamHanhChinhFinder(
		TrungTamHanhChinhFinder trungTamHanhChinhFinder) {

		this.trungTamHanhChinhFinder = trungTamHanhChinhFinder;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService
		getClassNameLocalService() {

		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService
			classNameLocalService) {

		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService
		getClassNameService() {

		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {

		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {

		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService
		getResourceLocalService() {

		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService
			resourceLocalService) {

		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService
		getUserLocalService() {

		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {

		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {

		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return LogSMSService.class.getName();
	}

	protected Class<?> getModelClass() {
		return LogSMS.class;
	}

	protected String getModelClassName() {
		return LogSMS.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = logSMSPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = org.oep.core.service.LogSMSLocalService.class)
	protected org.oep.core.service.LogSMSLocalService logSMSLocalService;

	@BeanReference(type = LogSMSService.class)
	protected LogSMSService logSMSService;

	@BeanReference(type = LogSMSPersistence.class)
	protected LogSMSPersistence logSMSPersistence;

	@BeanReference(type = LogSMSFinder.class)
	protected LogSMSFinder logSMSFinder;

	@BeanReference(type = org.oep.core.service.MailLocalService.class)
	protected org.oep.core.service.MailLocalService mailLocalService;

	@BeanReference(type = MailPersistence.class)
	protected MailPersistence mailPersistence;

	@BeanReference(type = org.oep.core.service.MappingVmapLocalService.class)
	protected org.oep.core.service.MappingVmapLocalService
		mappingVmapLocalService;

	@BeanReference(type = MappingVmapPersistence.class)
	protected MappingVmapPersistence mappingVmapPersistence;

	@BeanReference(type = org.oep.core.service.PhanQuyenLocalService.class)
	protected org.oep.core.service.PhanQuyenLocalService phanQuyenLocalService;

	@BeanReference(type = PhanQuyenPersistence.class)
	protected PhanQuyenPersistence phanQuyenPersistence;

	@BeanReference(type = org.oep.core.service.ThamSoLocalService.class)
	protected org.oep.core.service.ThamSoLocalService thamSoLocalService;

	@BeanReference(type = ThamSoPersistence.class)
	protected ThamSoPersistence thamSoPersistence;

	@BeanReference(type = ThamSoFinder.class)
	protected ThamSoFinder thamSoFinder;

	@BeanReference(type = org.oep.core.service.ThamSoLoaiLocalService.class)
	protected org.oep.core.service.ThamSoLoaiLocalService
		thamSoLoaiLocalService;

	@BeanReference(type = ThamSoLoaiPersistence.class)
	protected ThamSoLoaiPersistence thamSoLoaiPersistence;

	@BeanReference(
		type = org.oep.core.service.TrungTamHanhChinhLocalService.class
	)
	protected org.oep.core.service.TrungTamHanhChinhLocalService
		trungTamHanhChinhLocalService;

	@BeanReference(type = TrungTamHanhChinhPersistence.class)
	protected TrungTamHanhChinhPersistence trungTamHanhChinhPersistence;

	@BeanReference(type = TrungTamHanhChinhFinder.class)
	protected TrungTamHanhChinhFinder trungTamHanhChinhFinder;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ClassNameLocalService.class
	)
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ClassNameService.class
	)
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ResourceLocalService.class
	)
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.UserLocalService.class
	)
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.UserService.class
	)
	protected com.liferay.portal.kernel.service.UserService userService;

	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;

}